/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.logistica.proveedores.spec;

import com.logistica.proveedores.model.CalcularTotalFactura200Response;
import org.springframework.format.annotation.DateTimeFormat;
import com.logistica.proveedores.model.ErrorResponse;
import com.logistica.proveedores.model.Factura;
import com.logistica.proveedores.model.FacturaInput;
import com.logistica.proveedores.model.ListarFacturas200Response;
import java.time.LocalDate;
import com.logistica.proveedores.model.PagarFacturaRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-11T15:47:56.817647-06:00[America/Guatemala]")
@Validated
@Tag(name = "facturas", description = "Operaciones relacionadas con facturas")
@RequestMapping("${openapi.aPIDeGestinDeProveedoresYFacturas.base-path:/api/v1}")
public interface FacturasApi {

    /**
     * PUT /facturas/{id} : Actualizar una factura
     * Actualiza el estado o detalles de una factura
     *
     * @param id  (required)
     * @param facturaInput  (required)
     * @return Factura actualizada (status code 200)
     *         or Solicitud inválida (status code 400)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "actualizarFactura",
        summary = "Actualizar una factura",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura actualizada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Factura.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/facturas/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Factura> actualizarFactura(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id,
        @Parameter(name = "FacturaInput", description = "", required = true) @Valid @RequestBody FacturaInput facturaInput
    );


    /**
     * GET /facturas/{id}/calcular-total : Calcular total de la factura
     * Utiliza el componente C para calcular el total de la factura con impuestos
     *
     * @param id  (required)
     * @return Total calculado exitosamente (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "calcularTotalFactura",
        summary = "Calcular total de la factura",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Total calculado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CalcularTotalFactura200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/facturas/{id}/calcular-total",
        produces = { "application/json" }
    )
    ResponseEntity<CalcularTotalFactura200Response> calcularTotalFactura(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );


    /**
     * POST /facturas : Registrar una nueva factura
     * Crea una nueva factura asociada a un proveedor
     *
     * @param facturaInput  (required)
     * @return Factura creada exitosamente (status code 201)
     *         or Solicitud inválida (status code 400)
     *         or Proveedor no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "crearFactura",
        summary = "Registrar una nueva factura",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Factura creada exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Factura.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Proveedor no encontrado"),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/facturas",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Factura> crearFactura(
        @Parameter(name = "FacturaInput", description = "", required = true) @Valid @RequestBody FacturaInput facturaInput
    );


    /**
     * GET /facturas : Listar todas las facturas
     * Obtiene una lista paginada de todas las facturas del sistema
     *
     * @param proveedorId Filtrar por ID de proveedor (optional)
     * @param estado Filtrar por estado de la factura (optional)
     * @param fechaInicio Fecha de inicio para filtrado (formato YYYY-MM-DD) (optional)
     * @param fechaFin Fecha de fin para filtrado (formato YYYY-MM-DD) (optional)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return Lista de facturas obtenida exitosamente (status code 200)
     *         or Solicitud inválida (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "listarFacturas",
        summary = "Listar todas las facturas",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de facturas obtenida exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListarFacturas200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/facturas",
        produces = { "application/json" }
    )
    ResponseEntity<ListarFacturas200Response> listarFacturas(
        @Parameter(name = "proveedorId", description = "Filtrar por ID de proveedor") @Valid @RequestParam(value = "proveedorId", required = false) Long proveedorId,
        @Parameter(name = "estado", description = "Filtrar por estado de la factura") @Valid @RequestParam(value = "estado", required = false) String estado,
        @Parameter(name = "fechaInicio", description = "Fecha de inicio para filtrado (formato YYYY-MM-DD)") @Valid @RequestParam(value = "fechaInicio", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate fechaInicio,
        @Parameter(name = "fechaFin", description = "Fecha de fin para filtrado (formato YYYY-MM-DD)") @Valid @RequestParam(value = "fechaFin", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate fechaFin,
        @Parameter(name = "page", description = "") @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "") @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    );


    /**
     * GET /facturas/{id} : Obtener una factura por ID
     * Retorna los detalles de una factura específica
     *
     * @param id  (required)
     * @return Factura encontrada (status code 200)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "obtenerFacturaPorId",
        summary = "Obtener una factura por ID",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Factura encontrada", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Factura.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/facturas/{id}",
        produces = { "application/json" }
    )
    ResponseEntity<Factura> obtenerFacturaPorId(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );


    /**
     * POST /facturas/{id}/pagar : Registrar pago de factura
     * Marca una factura como pagada y registra la información del pago
     *
     * @param id  (required)
     * @param pagarFacturaRequest  (required)
     * @return Pago registrado exitosamente (status code 200)
     *         or La factura ya está pagada o no se puede pagar (status code 400)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "pagarFactura",
        summary = "Registrar pago de factura",
        tags = { "Facturas" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Pago registrado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Factura.class))
            }),
            @ApiResponse(responseCode = "400", description = "La factura ya está pagada o no se puede pagar"),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/facturas/{id}/pagar",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Factura> pagarFactura(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id,
        @Parameter(name = "PagarFacturaRequest", description = "", required = true) @Valid @RequestBody PagarFacturaRequest pagarFacturaRequest
    );

}
