/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.logistica.proveedores.spec;

import com.logistica.proveedores.model.ErrorResponse;
import com.logistica.proveedores.model.ListarProveedores200Response;
import com.logistica.proveedores.model.Proveedor;
import com.logistica.proveedores.model.ProveedorInput;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-09T15:32:00.964758700-06:00[America/Guatemala]")
@Validated
@Tag(name = "proveedores", description = "Operaciones relacionadas con proveedores")
@RequestMapping("${openapi.aPIDeGestinDeProveedoresYFacturas.base-path:/api/v1}")
public interface ProveedoresApi {

    /**
     * PUT /proveedores/{id} : Actualizar un proveedor
     * Actualiza la información de un proveedor existente
     *
     * @param id  (required)
     * @param proveedorInput  (required)
     * @return Proveedor actualizado exitosamente (status code 200)
     *         or Solicitud inválida (status code 400)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "actualizarProveedor",
        summary = "Actualizar un proveedor",
        tags = { "Proveedores" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Proveedor actualizado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Proveedor.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/proveedores/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Proveedor> actualizarProveedor(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id,
        @Parameter(name = "ProveedorInput", description = "", required = true) @Valid @RequestBody ProveedorInput proveedorInput
    );


    /**
     * POST /proveedores : Registrar un nuevo proveedor
     * Crea un nuevo proveedor en el sistema
     *
     * @param proveedorInput  (required)
     * @return Proveedor creado exitosamente (status code 201)
     *         or Solicitud inválida (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "crearProveedor",
        summary = "Registrar un nuevo proveedor",
        tags = { "Proveedores" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Proveedor creado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Proveedor.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/proveedores",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Proveedor> crearProveedor(
        @Parameter(name = "ProveedorInput", description = "", required = true) @Valid @RequestBody ProveedorInput proveedorInput
    );


    /**
     * DELETE /proveedores/{id} : Eliminar un proveedor
     * Elimina un proveedor del sistema (soft delete)
     *
     * @param id  (required)
     * @return Proveedor eliminado exitosamente (status code 204)
     *         or Recurso no encontrado (status code 404)
     *         or No se puede eliminar - tiene facturas asociadas (status code 409)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "eliminarProveedor",
        summary = "Eliminar un proveedor",
        tags = { "Proveedores" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Proveedor eliminado exitosamente"),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "No se puede eliminar - tiene facturas asociadas", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/proveedores/{id}",
        produces = { "application/json" }
    )
    ResponseEntity<Void> eliminarProveedor(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );


    /**
     * GET /proveedores : Listar todos los proveedores
     * Obtiene una lista paginada de todos los proveedores registrados
     *
     * @param page Número de página (comienza en 0) (optional, default to 0)
     * @param size Cantidad de elementos por página (optional, default to 10)
     * @param activo Filtrar por estado activo (optional)
     * @return Lista de proveedores obtenida exitosamente (status code 200)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "listarProveedores",
        summary = "Listar todos los proveedores",
        tags = { "Proveedores" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de proveedores obtenida exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListarProveedores200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/proveedores",
        produces = { "application/json" }
    )
    ResponseEntity<ListarProveedores200Response> listarProveedores(
        @Min(0) @Parameter(name = "page", description = "Número de página (comienza en 0)") @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(1) @Max(100) @Parameter(name = "size", description = "Cantidad de elementos por página") @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size,
        @Parameter(name = "activo", description = "Filtrar por estado activo") @Valid @RequestParam(value = "activo", required = false) Boolean activo
    );


    /**
     * GET /proveedores/{id} : Obtener un proveedor por ID
     * Retorna los detalles de un proveedor específico
     *
     * @param id ID único del proveedor (required)
     * @return Proveedor encontrado (status code 200)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "obtenerProveedorPorId",
        summary = "Obtener un proveedor por ID",
        tags = { "Proveedores" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Proveedor encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Proveedor.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/proveedores/{id}",
        produces = { "application/json" }
    )
    ResponseEntity<Proveedor> obtenerProveedorPorId(
        @Parameter(name = "id", description = "ID único del proveedor", required = true) @PathVariable("id") Long id
    );

}
