/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.umg.edu.gt.dev.spec;

import com.umg.edu.gt.dev.model.Cliente;
import com.umg.edu.gt.dev.model.ClienteInput;
import com.umg.edu.gt.dev.model.Pedido;
import com.umg.edu.gt.dev.model.PedidoInput;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-08T23:39:27.831609400-06:00[America/Guatemala]")
@Validated
@Tag(name = "api", description = "the api API")
@RequestMapping("${openapi.aPIComponenteAClientesYPedidos.base-path:}")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/v1/clientes : Crear un cliente
     *
     * @param clienteInput  (required)
     * @return Cliente creado correctamente (status code 201)
     *         or Datos invalidos (status code 400)
     */
    @Operation(
        operationId = "crearCliente",
        summary = "Crear un cliente",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Cliente creado correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            }),
            @ApiResponse(responseCode = "400", description = "Datos invalidos")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/clientes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Cliente> crearCliente(
        @Parameter(name = "ClienteInput", description = "", required = true) @Valid @RequestBody ClienteInput clienteInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"direccion\" : \"direccion\", \"id\" : 0, \"telefono\" : \"telefono\", \"nombre\" : \"nombre\", \"email\" : \"email\", \"codigoUnico\" : \"codigoUnico\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/v1/pedidos : Crear un pedido
     *
     * @param pedidoInput  (required)
     * @return Pedido creado correctamente (status code 201)
     *         or Datos invalidos (status code 400)
     */
    @Operation(
        operationId = "crearPedido",
        summary = "Crear un pedido",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Pedido creado correctamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            }),
            @ApiResponse(responseCode = "400", description = "Datos invalidos")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/pedidos",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Pedido> crearPedido(
        @Parameter(name = "PedidoInput", description = "", required = true) @Valid @RequestBody PedidoInput pedidoInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"codigoPedido\" : \"codigoPedido\", \"total\" : 3.616076749251911, \"clienteId\" : 6, \"subtotal\" : 7.061401241503109, \"impuestos\" : 9.301444243932576, \"id\" : 0, \"items\" : [ { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 }, { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/clientes : Listar todos los clientes
     *
     * @return Lista de clientes (status code 200)
     */
    @Operation(
        operationId = "listarClientes",
        summary = "Listar todos los clientes",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de clientes", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/clientes",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Cliente>> listarClientes(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"direccion\" : \"direccion\", \"id\" : 0, \"telefono\" : \"telefono\", \"nombre\" : \"nombre\", \"email\" : \"email\", \"codigoUnico\" : \"codigoUnico\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/pedidos : Listar todos los pedidos
     *
     * @return Lista de pedidos (status code 200)
     */
    @Operation(
        operationId = "listarPedidos",
        summary = "Listar todos los pedidos",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de pedidos", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/pedidos",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Pedido>> listarPedidos(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"codigoPedido\" : \"codigoPedido\", \"total\" : 3.616076749251911, \"clienteId\" : 6, \"subtotal\" : 7.061401241503109, \"impuestos\" : 9.301444243932576, \"id\" : 0, \"items\" : [ { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 }, { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/clientes/{id} : Obtener un cliente por ID
     *
     * @param id  (required)
     * @return Cliente encontrado (status code 200)
     *         or Cliente no encontrado (status code 404)
     */
    @Operation(
        operationId = "obtenerClientePorId",
        summary = "Obtener un cliente por ID",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/clientes/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Cliente> obtenerClientePorId(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"direccion\" : \"direccion\", \"id\" : 0, \"telefono\" : \"telefono\", \"nombre\" : \"nombre\", \"email\" : \"email\", \"codigoUnico\" : \"codigoUnico\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/v1/pedidos/{id} : Obtener un pedido por ID
     *
     * @param id  (required)
     * @return Pedido encontrado (status code 200)
     *         or Pedido no encontrado (status code 404)
     */
    @Operation(
        operationId = "obtenerPedidoPorId",
        summary = "Obtener un pedido por ID",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Pedido encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            }),
            @ApiResponse(responseCode = "404", description = "Pedido no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/pedidos/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Pedido> obtenerPedidoPorId(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"codigoPedido\" : \"codigoPedido\", \"total\" : 3.616076749251911, \"clienteId\" : 6, \"subtotal\" : 7.061401241503109, \"impuestos\" : 9.301444243932576, \"id\" : 0, \"items\" : [ { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 }, { \"productoNombre\" : \"productoNombre\", \"precioUnitario\" : 5.637376656633329, \"subtotal\" : 2.3021358869347655, \"id\" : 1, \"cantidad\" : 1 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
