/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.umg.edu.gt.dev.spec;

import com.umg.edu.gt.dev.model.Cliente;
import com.umg.edu.gt.dev.model.ClienteInput;
import com.umg.edu.gt.dev.model.ErrorResponse;
import com.umg.edu.gt.dev.model.ListarClientes200Response;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-08T01:40:33.368685200-06:00[America/Guatemala]")
@Validated
@Tag(name = "clientes", description = "Operaciones relacionadas con clientes")
@RequestMapping("${openapi.aPIDeGestinDeClientesYPedidos.base-path:/api/v1}")
public interface ClientesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /clientes/{id} : Actualizar un cliente
     * Actualiza la información de un cliente existente
     *
     * @param id ID único del cliente (required)
     * @param clienteInput  (required)
     * @return Cliente actualizado exitosamente (status code 200)
     *         or Solicitud inválida (status code 400)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "actualizarCliente",
        summary = "Actualizar un cliente",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clientes/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Cliente> actualizarCliente(
        @Parameter(name = "id", description = "ID único del cliente", required = true) @PathVariable("id") Long id,
        @Parameter(name = "ClienteInput", description = "", required = true) @Valid @RequestBody ClienteInput clienteInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fechaRegistro\" : \"2024-11-04T10:30:00Z\", \"direccion\" : \"Calle Principal 123, Zona 10\", \"id\" : 1, \"telefono\" : \"+502 1234-5678\", \"nombre\" : \"Juan Pérez\", \"email\" : \"juan.perez@example.com\", \"codigoUnico\" : \"CLI-20241104-001\", \"activo\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /clientes : Registrar un nuevo cliente
     * Crea un nuevo cliente en el sistema
     *
     * @param clienteInput  (required)
     * @return Cliente creado exitosamente (status code 201)
     *         or Solicitud inválida (status code 400)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "crearCliente",
        summary = "Registrar un nuevo cliente",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Cliente creado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clientes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Cliente> crearCliente(
        @Parameter(name = "ClienteInput", description = "", required = true) @Valid @RequestBody ClienteInput clienteInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fechaRegistro\" : \"2024-11-04T10:30:00Z\", \"direccion\" : \"Calle Principal 123, Zona 10\", \"id\" : 1, \"telefono\" : \"+502 1234-5678\", \"nombre\" : \"Juan Pérez\", \"email\" : \"juan.perez@example.com\", \"codigoUnico\" : \"CLI-20241104-001\", \"activo\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /clientes/{id} : Eliminar un cliente
     * Elimina un cliente del sistema (soft delete)
     *
     * @param id ID único del cliente (required)
     * @return Cliente eliminado exitosamente (status code 204)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "eliminarCliente",
        summary = "Eliminar un cliente",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Cliente eliminado exitosamente"),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/clientes/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Void> eliminarCliente(
        @Parameter(name = "id", description = "ID único del cliente", required = true) @PathVariable("id") Long id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /clientes : Listar todos los clientes
     * Obtiene una lista paginada de todos los clientes registrados en el sistema
     *
     * @param page Número de página (comienza en 0) (optional, default to 0)
     * @param size Cantidad de elementos por página (optional, default to 10)
     * @return Lista de clientes obtenida exitosamente (status code 200)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "listarClientes",
        summary = "Listar todos los clientes",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de clientes obtenida exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListarClientes200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clientes",
        produces = { "application/json" }
    )
    default ResponseEntity<ListarClientes200Response> listarClientes(
        @Min(0) @Parameter(name = "page", description = "Número de página (comienza en 0)") @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(1) @Max(100) @Parameter(name = "size", description = "Cantidad de elementos por página") @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalPages\" : 5, \"currentPage\" : 0, \"content\" : [ { \"fechaRegistro\" : \"2024-11-04T10:30:00Z\", \"direccion\" : \"Calle Principal 123, Zona 10\", \"id\" : 1, \"telefono\" : \"+502 1234-5678\", \"nombre\" : \"Juan Pérez\", \"email\" : \"juan.perez@example.com\", \"codigoUnico\" : \"CLI-20241104-001\", \"activo\" : true }, { \"fechaRegistro\" : \"2024-11-04T10:30:00Z\", \"direccion\" : \"Calle Principal 123, Zona 10\", \"id\" : 1, \"telefono\" : \"+502 1234-5678\", \"nombre\" : \"Juan Pérez\", \"email\" : \"juan.perez@example.com\", \"codigoUnico\" : \"CLI-20241104-001\", \"activo\" : true } ], \"totalElements\" : 50 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /clientes/{id} : Obtener un cliente por ID
     * Retorna los detalles de un cliente específico
     *
     * @param id ID único del cliente (required)
     * @return Cliente encontrado (status code 200)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "obtenerClientePorId",
        summary = "Obtener un cliente por ID",
        tags = { "Clientes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cliente.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clientes/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Cliente> obtenerClientePorId(
        @Parameter(name = "id", description = "ID único del cliente", required = true) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"fechaRegistro\" : \"2024-11-04T10:30:00Z\", \"direccion\" : \"Calle Principal 123, Zona 10\", \"id\" : 1, \"telefono\" : \"+502 1234-5678\", \"nombre\" : \"Juan Pérez\", \"email\" : \"juan.perez@example.com\", \"codigoUnico\" : \"CLI-20241104-001\", \"activo\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
