/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.umg.edu.gt.dev.spec;

import com.umg.edu.gt.dev.model.CalcularTotalPedido200Response;
import com.umg.edu.gt.dev.model.ErrorResponse;
import com.umg.edu.gt.dev.model.ListarPedidos200Response;
import com.umg.edu.gt.dev.model.Pedido;
import com.umg.edu.gt.dev.model.PedidoInput;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-08T01:40:33.368685200-06:00[America/Guatemala]")
@Validated
@Tag(name = "pedidos", description = "Operaciones relacionadas con pedidos")
@RequestMapping("${openapi.aPIDeGestinDeClientesYPedidos.base-path:/api/v1}")
public interface PedidosApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /pedidos/{id} : Actualizar un pedido
     * Actualiza el estado o detalles de un pedido
     *
     * @param id  (required)
     * @param pedidoInput  (required)
     * @return Pedido actualizado (status code 200)
     *         or Solicitud inválida (status code 400)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "actualizarPedido",
        summary = "Actualizar un pedido",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Pedido actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/pedidos/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Pedido> actualizarPedido(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id,
        @Parameter(name = "PedidoInput", description = "", required = true) @Valid @RequestBody PedidoInput pedidoInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"clienteNombre\" : \"Juan Pérez\", \"codigoPedido\" : \"PED-20241104-001\", \"estado\" : \"PENDIENTE\", \"total\" : 1120.0, \"clienteId\" : 1, \"subtotal\" : 1000.0, \"impuestos\" : 120.0, \"observaciones\" : \"observaciones\", \"fechaPedido\" : \"2024-11-04T10:30:00Z\", \"id\" : 1, \"items\" : [ { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 }, { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 } ], \"fechaEntregaEstimada\" : \"2024-11-10T00:00:00.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /pedidos/{id}/calcular-total : Calcular total del pedido
     * Utiliza el componente C para calcular el total del pedido incluyendo impuestos
     *
     * @param id  (required)
     * @return Total calculado exitosamente (status code 200)
     *         or Recurso no encontrado (status code 404)
     */
    @Operation(
        operationId = "calcularTotalPedido",
        summary = "Calcular total del pedido",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Total calculado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CalcularTotalPedido200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pedidos/{id}/calcular-total",
        produces = { "application/json" }
    )
    default ResponseEntity<CalcularTotalPedido200Response> calcularTotalPedido(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"total\" : 1120.0, \"pedidoId\" : 0, \"subtotal\" : 1000.0, \"impuestos\" : 120.0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /pedidos : Registrar un nuevo pedido
     * Crea un nuevo pedido asociado a un cliente
     *
     * @param pedidoInput  (required)
     * @return Pedido creado exitosamente (status code 201)
     *         or Solicitud inválida (status code 400)
     *         or Cliente no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "crearPedido",
        summary = "Registrar un nuevo pedido",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Pedido creado exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            }),
            @ApiResponse(responseCode = "400", description = "Solicitud inválida", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado"),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/pedidos",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Pedido> crearPedido(
        @Parameter(name = "PedidoInput", description = "", required = true) @Valid @RequestBody PedidoInput pedidoInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"clienteNombre\" : \"Juan Pérez\", \"codigoPedido\" : \"PED-20241104-001\", \"estado\" : \"PENDIENTE\", \"total\" : 1120.0, \"clienteId\" : 1, \"subtotal\" : 1000.0, \"impuestos\" : 120.0, \"observaciones\" : \"observaciones\", \"fechaPedido\" : \"2024-11-04T10:30:00Z\", \"id\" : 1, \"items\" : [ { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 }, { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 } ], \"fechaEntregaEstimada\" : \"2024-11-10T00:00:00.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /pedidos : Listar todos los pedidos
     * Obtiene una lista paginada de todos los pedidos del sistema
     *
     * @param clienteId Filtrar por ID de cliente (optional)
     * @param estado Filtrar por estado del pedido (optional)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return Lista de pedidos obtenida exitosamente (status code 200)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "listarPedidos",
        summary = "Listar todos los pedidos",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de pedidos obtenida exitosamente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListarPedidos200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pedidos",
        produces = { "application/json" }
    )
    default ResponseEntity<ListarPedidos200Response> listarPedidos(
        @Parameter(name = "clienteId", description = "Filtrar por ID de cliente") @Valid @RequestParam(value = "clienteId", required = false) Long clienteId,
        @Parameter(name = "estado", description = "Filtrar por estado del pedido") @Valid @RequestParam(value = "estado", required = false) String estado,
        @Parameter(name = "page", description = "") @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "") @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"totalPages\" : 1, \"currentPage\" : 5, \"content\" : [ { \"clienteNombre\" : \"Juan Pérez\", \"codigoPedido\" : \"PED-20241104-001\", \"estado\" : \"PENDIENTE\", \"total\" : 1120.0, \"clienteId\" : 1, \"subtotal\" : 1000.0, \"impuestos\" : 120.0, \"observaciones\" : \"observaciones\", \"fechaPedido\" : \"2024-11-04T10:30:00Z\", \"id\" : 1, \"items\" : [ { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 }, { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 } ], \"fechaEntregaEstimada\" : \"2024-11-10T00:00:00.000+00:00\" }, { \"clienteNombre\" : \"Juan Pérez\", \"codigoPedido\" : \"PED-20241104-001\", \"estado\" : \"PENDIENTE\", \"total\" : 1120.0, \"clienteId\" : 1, \"subtotal\" : 1000.0, \"impuestos\" : 120.0, \"observaciones\" : \"observaciones\", \"fechaPedido\" : \"2024-11-04T10:30:00Z\", \"id\" : 1, \"items\" : [ { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 }, { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 } ], \"fechaEntregaEstimada\" : \"2024-11-10T00:00:00.000+00:00\" } ], \"totalElements\" : 6 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /pedidos/{id} : Obtener un pedido por ID
     * Retorna los detalles de un pedido específico
     *
     * @param id  (required)
     * @return Pedido encontrado (status code 200)
     *         or Recurso no encontrado (status code 404)
     *         or Error interno del servidor (status code 500)
     */
    @Operation(
        operationId = "obtenerPedidoPorId",
        summary = "Obtener un pedido por ID",
        tags = { "Pedidos" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Pedido encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Pedido.class))
            }),
            @ApiResponse(responseCode = "404", description = "Recurso no encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Error interno del servidor", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pedidos/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Pedido> obtenerPedidoPorId(
        @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"clienteNombre\" : \"Juan Pérez\", \"codigoPedido\" : \"PED-20241104-001\", \"estado\" : \"PENDIENTE\", \"total\" : 1120.0, \"clienteId\" : 1, \"subtotal\" : 1000.0, \"impuestos\" : 120.0, \"observaciones\" : \"observaciones\", \"fechaPedido\" : \"2024-11-04T10:30:00Z\", \"id\" : 1, \"items\" : [ { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 }, { \"productoNombre\" : \"Laptop HP\", \"precioUnitario\" : 500.0, \"subtotal\" : 1000.0, \"id\" : 0, \"cantidad\" : 2 } ], \"fechaEntregaEstimada\" : \"2024-11-10T00:00:00.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
